# Generated by Django 3.0.3 on 2020-02-05 03:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('joined', models.DateTimeField(auto_now=True)),
                ('number_test', models.BigIntegerField(default=0)),
            ],
        ),
    ]
